# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      # Run the linter.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat
      - id: djlint
        args: ['--ignore=H006,H021,H030,H031']
      - id: djlint-reformat-jinja
      - id: djlint-jinja
        args: ['--ignore=H006,H021,H030,H031']
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
# - repo: https://github.com/pre-commit/mirrors-csslint
#   rev: v1.0.5
#   hooks:
#     - id: csslint
# - repo: https://github.com/thibaudcolas/pre-commit-stylelint
#   rev: v14.4.0
#   hooks:
#     - id: stylelint
#       additional_dependencies:
#         - stylelint@14.4.0
#         - stylelint-config-recommended
#         - stylelint-config-standard
#         - stylelint-config-standard-scss@3.0.0
